apiVersion: apps/v1
kind: Deployment
metadata:
  name: testeargo
spec:
  selector:
    matchLabels:
      app: testeargo
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: testeargo
    spec:
#      affinity:
#        podAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: security
#                    operator: NotIn
#                    values:
#                      - k8s-node-17
#                      - k8s-node-128
#              topologyKey: kubernetes.io/hostname
      containers:
        - name: testeargo-container
          image: nginx
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 60
      #nodeSelector:
      #  kubernetes.io/hostname: ${NODE_KUBERNETES}
      nodeSelector:
        general: "true"
      imagePullSecrets:
        - name: registrypullsecret

---
apiVersion: v1
kind: Service
metadata:
  name: testeargo-service
spec:
  ports:
    - port: 8080
  selector:
    app: testeargo
